on:
  push:
    branches:
      - '**'

name: Discord Notification

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Push
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
