on:
  push:
    branches:
      - '**'
  issues:
    types: [opened, edited, deleted, closed, reopened, assigned, unassigned]

name: Discord Notification

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@master
